### ISSUE TITLE
Does the module support multiple sitegroups?

### ISSUE THREAD

**Issue by roman-yagodin** [SCullman/dnn-sitegroups#1]
I've tested SiteGroups module on DNN v8.0.4 with no major issues so far. But does the module have support for multiple sitegroups, or just a single one?

**Comment by SCullman** [comment]
Sure, Why do think it is limited to a single one? 
The module is just an editor for the sitegroups, everything else is managed by dnn itself.

**Comment by roman-yagodin** [comment]
I just not saw any UI to create additional sitegroup after the first one is created - but it showed up after I've added more sites to the installation.
